# Generated by Django 5.0 on 2024-02-06 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apk", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="creted",
            new_name="created",
        ),
    ]
