# Generated by Django 5.0 on 2024-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apk", "0002_rename_creted_watchlist_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="storyline",
            field=models.CharField(max_length=300),
        ),
    ]
